version: '2'
services:
  redis:
    image: redis:2.8.19
    network_mode: "service:frontend"
  frontend:
    env_file: .env
    container_name: frontend
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
